services:
  solurepair_keycloak:
    image: solurepair-keycloak
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # ADMIN CONFIG
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      # FEATURES CONFIG
      - KC_FEATURES=token-exchange:v1,admin-fine-grained-authz:v1
      # DATABASE CONFIG
      - KC_DB=postgres
      - KC_DB_USERNAME=
      - KC_DB_PASSWORD=
      - KC_DB_URL=
      # HOSTANAME CONFIG
      - KC_HOSTNAME=${KC_HOSTNAME}
      - KC_PROXY=edge
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
    command: ["start", "--optimized"]
    restart: unless-stopped
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
