services:
  keycloak:
    image: solurepair-keycloak
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      # ADMIN CONFIG
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      # FEATURES CONFIG
      - KC_FEATURES=token-exchange:v1,admin-fine-grained-authz:v1
      # DATABASE CONFIG
      - KC_DB=postgres
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
      - KC_DB_URL=jdbc:postgresql://postgres/${POSTGRES_DB}
      # HOSTANAME CONFIG
      - KC_HOSTNAME=${KC_HOSTNAME}
      - KC_PROXY=edge
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
    command: ["start", "--optimized"]
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: